export const products = [
  {
    id: 0,
    name: "Copper Tea Kettle",
    price: 395.0,
    category: "Pots",
    description: [
      "Solid stainless steel constructed teakettle",
      "Whistling teakettle alerts when water is boiling. Cooktop Compatibility: Electric Coil, Electric Smooth Top, Gas",
      "Hand wash recommended",
      "Bakelite handles and stoppers",
    ],
    image: "https://i.pinimg.com/originals/fd/10/fe/fd10fe53338d7c6099407cf7595b5ac2.jpg",
  },
  {
    id: 1,
    name: "Minimal Chargers - Charcoal",
    price: 1099.0,
    category: "Plates",
    description: [
      "Clean, organic and minimal with a matte satin finish.",
      "Flat in shape with a slightly raised edge, the perfect canvas for any presentation.",
      "Use as charger plate or serving platter! ",
    ],
    image: "https://i.pinimg.com/originals/ce/37/4d/ce374d5b06293e39ed484a67c480f642.jpg",
  },
  {
    id: 2,
    name: "Mora Ceramic Flat Bowls",
    price: 860.0,
    category: "Bowls",
    description: [
      'This is more than a bowl. Mora is Latin for "Pause", acting as a reminder to slow down in your amazing life. You are always being told to do more, to go faster, to be better, but it\'s time for you to slow down every once in a while and hit pause. Your Mora bowls can help you do that. Whether you are eating noodles, salad, or anything else, every time you use a Mora bowl it is a reminder to hit pause, give yourself some me time, and practice mindful eating.',
    ],
    image: "https://i.pinimg.com/originals/9f/2d/4c/9f2d4c6b96dd5aaa0e3bd94fcf950053.jpg",
  },
  {
    id: 3,
    name: "Qualia Ebony Highball Glasses",
    price: 560.0,
    category: "Glass",
    description: [
      "Qualia Ebony Highball Glasses In Clear/black (Set Of 4) Black/clear",
      "Add a touch of modern elegance to your table setting.",
      "Beautifully mouth-blown and hand-crafted, the Ebony Highball Glasses feature a classic and sophisticated design, perfect for formal or casual occasion.",
    ],
    image: "https://i.pinimg.com/originals/27/db/a0/27dba0a0dc0cceb5e239d73d06bbf385.jpg",
  },
  {
    id: 4,
    name: "Frosted Silverware",
    price: 210.0,
    category: "Silverware",
    description: ["Frost Stainless Steel.", "5 Pieces per set", "Includes Wire Caddy."],
    image: "https://i.pinimg.com/originals/48/7a/8b/487a8b8391fce2d1d9a34ba7dd69b9bb.jpg",
  },
  {
    id: 5,
    name: "Acacia Wood Oblong Plates - Set of 2",
    price: 750.0,
    category: "Plates",
    description: [
      "Lightweight plates are the perfect accompaniment for snacks.",
      "Hand carved and sanded from sustainable acacia wood. Natural tones vary.",
      'Dimensions: 7"l x 5"w. Care Instructions: Wash before first use.',
      "Hand wash using a soft sponge and mild soap. Do not soak pieces. Not dishwasher safe. Dry thoroughly, then let air dry overnight. To enhance the natural beauty of the wood, periodically rub with food-safe mineral oil.",
    ],
    image: "https://i.pinimg.com/originals/22/c6/49/22c6492f4373ae49ed47b683cd58d1f2.jpg",
  },
  {
    id: 6,
    name: "Floral Leaf Glass Cup and Teapot",
    price: 600.0,
    category: "Pots",
    description: [
      "These teapots and cup boast a pretty floral design that simply bursts of spring inspiration.",
      "There are two teapot sizes to choose between, and a glass cup perfect for enjoying tea.",
      "You will love brewing your favorite tea each time that you use the teapot.",
      "Enjoy green tea, jasmine tea, or perhaps a refreshing mint.",
      "A pretty housewarming gift Teapots are offered in 2 sizes Package list: 1 teacup or 1 teapot in choice of size.",
    ],
    image: "https://i.pinimg.com/originals/ca/f7/83/caf7836575873fa4face60a95b3aff16.png",
  },
  {
    id: 7,
    name: "Pyrex Wooden Storage 4-Piece Set",
    price: 750,
    category: "Containers",
    description: [
      "4-cup lidded round.",
      "Durable, high-quality, tempered Pyrex® glass for easy cleanup Glass containers resist stains and do not absorb food odors or flavors",
      "Stylishly displays dry foods and other household items.",
      'ackage dimensions: 6.6"L x 6.1"W x 6.6"H Total weight: 3.5 lbs.',
    ],
    image: "https://i.pinimg.com/originals/3e/42/2e/3e422e27ce0da71d6ed3776864dec98c.png",
  },
  {
    id: 8,
    name: "Court Low Bowls - Set of 8",
    price: 900.0,
    category: "Bowls",
    description: [
      "A beautiful addition to the holiday buffet table, this set of white porcelain low bowls combines squares and curves in a dynamic contemporary design.",
      'View all Court Dinnerware Court Low Bowls, Set of 8. 7.75"Wx7.75"Dx2"H Porcelain 30 oz.',
      "Dishwasher-, microwave- and oven-safe to 350 degrees.",
      "Imported",
    ],
    image: "https://i.pinimg.com/originals/3c/af/a2/3cafa2a39291b1b9f364c7c7fd9a790c.jpg",
  },
  {
    id: 9,
    name: "Logan Stacking Dinnerware - Set of 8",
    price: 1100.0,
    category: "Plates",
    description: [
      "Save space in the kitchen cabinet with Logan stacking dinnerware.",
      "After washing, set bowls, plates, cups and more one on top of the other. ",
      "Dishwasher-, microwave- and oven-safe to 350 degrees.",
      'Set of 8. 12.75"Wx11"Lx2"1.2"H Porcelain.',
    ],
    image: "	https://i.pinimg.com/originals/e6/27/62/e62762a1805ec44312bad7a743967238.jpg",
  },
  {
    id: 10,
    name: "Kaloh Stoneware Oil & Vinegar Dispensers - Set of 2",
    price: 400.0,
    category: "Containers",
    description: [
      '2.75"diam. x 10.5"h. 18 fluid oz capacity.',
      "Glazed stoneware. Oil container in White finish.",
      "Vinegar container in Gray finish.",
      "Acacia wood lid.",
    ],
    image: "https://i.pinimg.com/originals/8a/07/c4/8a07c44f0ee7f33b9c9b039035f066bf.png",
  },
  {
    id: 11,
    name: "Kamikoto Knives - Kuro Series - Set of 3",
    price: 850.0,
    category: "Cutlery",
    description: [
      "Presenting the hardest blades we've ever made.",
      "Crafted out of zirconium dioxide and sharpened by Kamikoto.",
      "Hand wash recommended",
      '8.05"Blade Length x 12"Total Length x 2.10"Height',
    ],
    image: "https://i.pinimg.com/originals/c3/fe/d7/c3fed77abadbfcf6cb82a4487f7d9b1d.jpg",
  },
  {
    id: 12,
    name: "Coffee Mug - Set of 6",
    price: 800.0,
    category: "Glass",
    description: [
      "Bruntmor 16 oz ceramic mugs are the perfect addition to your kitchen cupboard or cafe serve ware.",
      "Dishwasher safe and sturdy, these contemporary mugs will last.",
      "The material allows for a quick cleanup and the mugs are great for everyday use.",
      "These are fantastic gifts for housewarmings, wedding showers, work parties, and more.",
    ],
    image: "https://i.pinimg.com/originals/09/d3/13/09d31340c8d23be90a653a6ed8f85db2.jpg",
  },
  {
    id: 13,
    name: "Acacia Wooden Utensils for Cooking - Set of 4",
    price: 800.0,
    category: "Spoons",
    description: [
      "The wooden utensils are crafted from 100% acacia wood,which feature lightweight,solid and resistant to water, stain and odour absorption.",
      "Due to its material, the set will not scratch or damage your expensive non-stick pots and pans.Just use them without concern.",
      "With just warm water or detergent by hand,the set become clean as new.After usage, just hang it in your kitchen since there are hanging holes in the end of the items.",
      '7.95"L.x1.5"W.(Handle)',
    ],
    image: "https://i.pinimg.com/originals/60/f5/84/60f5848180f7d626fea30d759492277b.jpg",
  },
  {
    id: 14,
    name: "Hand-painted Traditional Spanish Lebrillo",
    price: 650.0,
    category: "Plates",
    description: [
      "Hand-painted traditional Spanish Lebrillo design with birds and pomegranates.",
      'Diameter 10" Handmade and hand painted in Southern Spain Terracotta Clay.',
      "Dishwasher and Microwave safe Plates can be used for dining, decoration or wall mounted for display.",
      "It's a work of art! *Colors may vary slightly from the image online/actual product*Because these ceramics are made and painted by hand, each may have a slight variation in pattern.",
    ],
    image: "https://i.pinimg.com/originals/a9/c7/9a/a9c79a4c5e8250bde4e3f4f89d3b05e3.jpg",
  },
  {
    id: 15,
    name: "Viners Assure - Set of 4",
    price: 900.0,
    category: "Cutlery",
    description: [
      "Part of the Viners Assure collection, this four-piece kitchen knife set features a unique squared tip to maximise safe use within the kitchen as well as being stylish.",
      "These kitchen knives are highly functional with food preparation and carving and boast elegant, curved soft touch handles for optimum comfort.",
      "Finished with a black non-stick coating which helps reduce cutting friction, these kitchen knives are hand wash only.",
      '7.05"Blade Length x 11"Total Length x 2.10"Height',
    ],
    image: "https://i.pinimg.com/originals/d1/72/28/d172286881bd1f8558b4c9846f9881b2.jpg",
  },
];
